const { neon } = require('@neondatabase/serverless');

// Ensure DATABASE_URL is present
if (!process.env.DATABASE_URL) {
  console.error('Error: DATABASE_URL environment variable is missing.');
  console.error('Please make sure you have it in your .env file and run the script with:');
  console.error('node --env-file=.env seed.js');
  process.exit(1);
}

const sql = neon(process.env.DATABASE_URL);

// ----------------------------------------------------
// 📝 EDIT THIS ARRAY WITH YOUR REAL SUBJECT DATA
// ----------------------------------------------------
const subjectsToSeed = [
  {
    code: '18B11MA111',
    name: 'MATHEMATICS-I',
    semester: 1,
    credits: 4.0,
    status: 'passed',
    grade: 'P',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B11PH111',
    name: 'PHYSICS-I',
    semester: 1,
    credits: 4.0,
    status: 'passed',
    grade: 'P',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B11CI111',
    name: 'SOFTWARE DEVELOPMENT FUNDAMENTALS',
    semester: 1,
    credits: 4.0,
    status: 'passed',
    grade: 'C',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B11HS111',
    name: 'ENGLISH',
    semester: 1,
    credits: 3.0,
    status: 'passed',
    grade: 'P',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B17CI171',
    name: 'SOFTWARE DEVELOPMENT LAB',
    semester: 1,
    credits: 2.0,
    status: 'passed',
    grade: 'B+',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B17ME171',
    name: 'WORKSHOP',
    semester: 1,
    credits: 1.5,
    status: 'passed',
    grade: 'P',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B17PH171',
    name: 'PHYSICS LAB-I',
    semester: 1,
    credits: 1.0,
    status: 'passed',
    grade: 'P',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '21B19GE199',
    name: 'BRIDGE COURSE',
    semester: 1,
    credits: 0.0,
    status: 'passed',
    grade: 'NP',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B19HS491',
    name: 'HUMAN VALUES AND PROFESSIONAL ETHICS',
    semester: 1,
    credits: 0.0,
    status: 'passed',
    grade: 'NP',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B11MA211',
    name: 'DISCRETE MATHEMATICS',
    semester: 2,
    credits: 4.0,
    status: 'passed',
    grade: 'P',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B11EC211',
    name: 'ELECTRICAL SCIENCE',
    semester: 2,
    credits: 4.0,
    status: 'failed',
    grade: 'AB',
    attempts: 1,
    exam_session: null,
    remarks: 'Absent from exam',
  },
  {
    code: '18B11CI211',
    name: 'OBJECT ORIENTED PROGRAMMING',
    semester: 2,
    credits: 4.0,
    status: 'failed',
    grade: 'AB',
    attempts: 1,
    exam_session: null,
    remarks: 'Absent from exam',
  },
  {
    code: '18B11PH211',
    name: 'PHYSICS-2',
    semester: 2,
    credits: 4.0,
    status: 'failed',
    grade: 'AB',
    attempts: 1,
    exam_session: null,
    remarks: 'Absent from exam',
  },
  {
    code: '21B11HS211',
    name: 'LIFE SKILLS AND EFFECTIVE COMMUNICATION',
    semester: 2,
    credits: 2.0,
    status: 'passed',
    grade: 'P',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B17ME272',
    name: 'ENGINEERING DRAWING & DESIGN LAB',
    semester: 2,
    credits: 1.5,
    status: 'passed',
    grade: 'C',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B17EC271',
    name: 'ELECTRICAL SCIENCE LAB',
    semester: 2,
    credits: 1.0,
    status: 'passed',
    grade: 'C',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B17CI271',
    name: 'OBJECT ORIENTED PROGRAMMING LAB',
    semester: 2,
    credits: 1.0,
    status: 'passed',
    grade: 'P',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B17PH271',
    name: 'PHYSICS LAB-2',
    semester: 2,
    credits: 1.0,
    status: 'passed',
    grade: 'P',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B11CI311',
    name: 'DATA STRUCTURES',
    semester: 3,
    credits: 4.0,
    status: 'passed',
    grade: 'P',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B11EC311',
    name: 'DIGITAL SYSTEMS AND MICROPROCESSORS',
    semester: 3,
    credits: 4.0,
    status: 'failed',
    grade: 'AB',
    attempts: 1,
    exam_session: null,
    remarks: 'Absent from exam',
  },
  {
    code: '18B11CI312',
    name: 'DATABASE SYSTEMS',
    semester: 3,
    credits: 3.0,
    status: 'passed',
    grade: 'P',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B11HS312',
    name: 'TECHNIQUES FOR DECISION MAKING',
    semester: 3,
    credits: 3.0,
    status: 'passed',
    grade: 'C',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B17CI373',
    name: 'ADVANCED PROGRAMMING LAB-1',
    semester: 3,
    credits: 2.0,
    status: 'passed',
    grade: 'P',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B19GE399',
    name: 'ENVIRONMENTAL SCIENCE',
    semester: 3,
    credits: 2.0,
    status: 'passed',
    grade: 'P',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B17CI371',
    name: 'DATA STRUCTURES LAB',
    semester: 3,
    credits: 1.0,
    status: 'passed',
    grade: 'P',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B17CI372',
    name: 'DATABASE SYSTEMS LAB',
    semester: 3,
    credits: 1.0,
    status: 'passed',
    grade: 'P',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B17EC371',
    name: 'DIGITAL SYSTEMS AND MICROPROCESSORS LAB',
    semester: 3,
    credits: 1.0,
    status: 'failed',
    grade: 'AB',
    attempts: 1,
    exam_session: null,
    remarks: 'Absent from exam',
  },
  {
    code: '18B17CI307',
    name: 'UI/UX LAB',
    semester: 3,
    credits: 1.0,
    status: 'passed',
    grade: 'C',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '21B19HS399',
    name: 'PROFESSIONAL COMMUNICATION PRACTICE',
    semester: 3,
    credits: 0.0,
    status: 'passed',
    grade: 'NP',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B11CI412',
    name: 'ALGORITHMS AND PROBLEM SOLVING',
    semester: 4,
    credits: 4.0,
    status: 'passed',
    grade: 'P',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B11CI415',
    name: 'ARTIFICIAL INTELLIGENCE & APPLICATION',
    semester: 4,
    credits: 4.0,
    status: 'passed',
    grade: 'P',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B11CI411',
    name: 'COMPUTER NETWORKS',
    semester: 4,
    credits: 3.0,
    status: 'passed',
    grade: 'B+',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B14HS441',
    name: 'CONCEPT OF DIGITAL MARKETING',
    semester: 4,
    credits: 3.0,
    status: 'passed',
    grade: 'C',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B11CI413',
    name: 'OPERATING SYSTEMS',
    semester: 4,
    credits: 3.0,
    status: 'failed',
    grade: 'AB',
    attempts: 1,
    exam_session: null,
    remarks: 'Absent from exam',
  },
  {
    code: '18B28CI408',
    name: 'MOBILE AND APPLICATION DEVELOPMENT LAB',
    semester: 4,
    credits: 2.0,
    status: 'passed',
    grade: 'P',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B17CI475',
    name: 'AI & APPLICATION LAB',
    semester: 4,
    credits: 1.0,
    status: 'passed',
    grade: 'C',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B17CI472',
    name: 'ALGORITHMS LAB',
    semester: 4,
    credits: 1.0,
    status: 'passed',
    grade: 'C',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B17CI471',
    name: 'COMPUTER NETWORKS LAB',
    semester: 4,
    credits: 1.0,
    status: 'failed',
    grade: 'AB',
    attempts: 1,
    exam_session: null,
    remarks: 'Absent from exam',
  },
  {
    code: '18B17CI473',
    name: 'OPERATING SYSTEMS LAB',
    semester: 4,
    credits: 1.0,
    status: 'passed',
    grade: 'P',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B11MA511',
    name: 'PROBABILITY THEORY AND RANDOM PROCESSES',
    semester: 5,
    credits: 4.0,
    status: 'passed',
    grade: 'P',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B11CI511',
    name: 'THEORY OF COMPUTATION',
    semester: 5,
    credits: 4.0,
    status: 'passed',
    grade: 'P',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B11CI917',
    name: 'DATA ANALYTICS SYSTEMS AND ALGORITHMS',
    semester: 5,
    credits: 3.0,
    status: 'passed',
    grade: 'P',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B19CI591',
    name: 'MINOR PROJECT- 1',
    semester: 5,
    credits: 3.0,
    status: 'passed',
    grade: 'B+',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B17CI573',
    name: 'ADVANCED PROGRAMMING LAB-2',
    semester: 5,
    credits: 2.0,
    status: 'failed',
    grade: 'AB',
    attempts: 1,
    exam_session: null,
    remarks: 'Absent from exam',
  },
  {
    code: '21B14HS547',
    name: 'CONCEPT OF ECONOMICS',
    semester: 5,
    credits: 3.0,
    status: 'passed',
    grade: 'P',
    attempts: 1,
    exam_session: null,
    remarks: '',
  },
  {
    code: '18B14MA544',
    name: 'FUZZY SYSTEMS & APPLICATIONS',
    semester: 5,
    credits: 3.0,
    status: 'dropped',
    grade: 'NR',
    attempts: 1,
    exam_session: null,
    remarks: 'Dropped course',
  },
  {
    code: '18B17CI507',
    name: 'OPEN SOURCE SOFTWARE LAB',
    semester: 6,
    credits: 1.0,
    status: 'dropped',
    grade: 'NR',
    attempts: 1,
    exam_session: null,
    remarks: 'Dropped course',
  },
];

async function seed() {
  try {
    console.log('⏳ Seeding default settings...');
    await sql`
      INSERT INTO settings (id, degree_name, university_name, total_credits, passing_grade, theme)
      VALUES (1, 'Bachelor of Technology', 'Your University', 120, 'D', 'light')
      ON CONFLICT (id) DO NOTHING
    `;
    console.log('✅ Settings initialized successfully.');

    console.log(`⏳ Seeding ${subjectsToSeed.length} subjects...`);
    for (const s of subjectsToSeed) {
      await sql`
        INSERT INTO subjects (code, name, semester, credits, grade, status, attempts, exam_session, remarks)
        VALUES (${s.code}, ${s.name}, ${s.semester}, ${s.credits}, ${s.grade}, ${s.status}, ${s.attempts}, ${s.exam_session}, ${s.remarks})
        ON CONFLICT (code, semester) DO UPDATE SET
          name = EXCLUDED.name,
          credits = EXCLUDED.credits,
          grade = EXCLUDED.grade,
          status = EXCLUDED.status,
          attempts = EXCLUDED.attempts,
          exam_session = EXCLUDED.exam_session,
          remarks = EXCLUDED.remarks,
          updated_at = CURRENT_TIMESTAMP
      `;
      console.log(`   - Seeded/Updated: ${s.code} (${s.name})`);
    }

    console.log('🎉 Database seeding completed successfully!');
  } catch (error) {
    console.error('❌ Seeding failed:', error);
  }
}

seed();
